### ISSUE TITLE
Installation Issue on mac

### ISSUE THREAD

**Issue by avichaturvedi** [dynamics-of-stellar-systems/dynamite#279]
Dear all, 

I am new to DYNAMITE and am trying to install it on my system. Here are the steps which I followed to install it on my system.. 

1) Following the steps mentioned on the website, I installed the latest version dynamite in my home directory and modified the '.zshfile' as follows: 

<img width="914" alt="Screenshot 2023-02-15 at 14 49 57" src="https://user-images.githubusercontent.com/125473899/219049745-106f2290-89c0-405f-8a42-7d5d9c57c5ca.png">

2) I am able to import the dynamite in the jupyter notebook tutorials and the installed path shows something like this : 

<img width="1014" alt="Screenshot 2023-02-15 at 14 52 05" src="https://user-images.githubusercontent.com/125473899/219050128-9964c447-357f-471a-8e9f-2bf09276dc7f.png">

3) I am able to perform all the steps of the tutorial notebook, but on running the "model.get_orblib()", I am getting following error : 

<img width="1152" alt="Screenshot 2023-02-15 at 14 53 15" src="https://user-images.githubusercontent.com/125473899/219050425-35adfa46-dae0-4039-a27d-fcc3dc766e73.png">

 It seems that it may be related to path issue ? Please let me if you have any suggestions. 

Thanks
Avinash

**Comment by maindlt** [comment]
Hi @avichaturvedi,

I just verified that the same notebook works on my Mac. It looks like in your case the Fortran executables are not there or not where DYNAMITE excepts them... Just to make sure:
- After installing GALAHAD and compiling legacy_fortran you should have the executables `modelgen` `orbitstart` `orblib` `orblib_new_mirror` `triaxmass` `triaxmassbin` `triaxnnls_CRcut` `triaxnnls_noCRcut` in your `dynamite/legacy_fortran` directory. Deviating from the instructions at https://dynamics.univie.ac.at/dynamite_docs/getting_started/installation.html you can make 100% sure that you compile the Fortran files from scratch by saying `make distclean; make all` instead of `make all` in the `legacy_fortran` directory.
- Once the mentioned executables are there, issue the `python setup.py instal`l or `python setup.py install --user` command as described in the installation guide. The latter uses your user directory for installation and is useful on systems you don't have root privileges on, such as a cluster.
- The setup script produces much output which might give some hints. In case of a successful installation, the compiled Fortran executables should be in `.../lib/python3.8/site-packages/dynamite-3.0.0-py3.8egg/legacy_fortran/`
- If everything look ok, please test by executing `test_nnls.py` in the `dynamite/dev_test` directory.

Looking forward to your reply and kind regards,
Thomas

**Comment by maindlt** [comment]
Hi @avichaturvedi,

have you succeeded installing DYNAMITE? Please feel free to re-open this issue in case you still encounter problems...

All the best,
Thomas
