### ISSUE TITLE
Error due to having only one iteration done?

### ISSUE THREAD

**Issue by gsantucci90** [dynamics-of-stellar-systems/dynamite#293]
Hi all,

I had a few galaxies where only one iteration was done for the first run. So when I ran dynamite again I got this error:

> Using DYNAMITE version: 3.0.0
> Located at: ['/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite']
> Starting galaxy 16791969
> <class 'dynamite.physical_system.System'>
> <class 'dynamite.config_reader.Settings'>
>        m-bh         a-bh f-dh      q-stars       p-stars u-stars         ml        
> ------------------ ----- ---- ------------------ ------- ------- ------------------
> 125338987.46781121 1e-06 10.0 0.5987431772592958    0.99  0.9999 2.9693735398325796
> 1 kinematics data sets in system
> Traceback (most recent call last):
>   File "run_dyn.py", line 123, in <module>
>     run_user_test(gal)
>   File "run_dyn.py", line 65, in run_user_test
>     smi = dyn.model_iterator.ModelIterator(config=c)
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite/model_iterator.py", line 92, in __init__
>     status = model_inner_iterator.run_iteration()
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite/model_iterator.py", line 496, in run_iteration
>     self.par_generator.generate(current_models=self.all_models)
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite/parameter_space.py", line 451, in generate
>     self.check_stopping_critera()
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite/parameter_space.py", line 545, in check_stopping_critera
>     self.check_specific_stopping_critera()
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/dynamite-3.0.0-py3.8.egg/dynamite/parameter_space.py", line 595, in check_specific_stopping_critera
>     previous_chi2 = np.nanmin(models1[self.chi2])
>   File "<__array_function__ internals>", line 180, in nanmin
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/numpy-1.23.2-py3.8-linux-x86_64.egg/numpy/lib/nanfunctions.py", line 350, in nanmin
>     res = np.amin(a, axis=axis, out=out, **kwargs)
>   File "<__array_function__ internals>", line 180, in amin
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/numpy-1.23.2-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 2918, in amin
>     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/numpy-1.23.2-py3.8-linux-x86_64.egg/numpy/core/fromnumeric.py", line 84, in _wrapreduction
>     return reduction(axis=axis, out=out, **passkwargs)
>   File "/home/gsantucc/.local/lib/python3.8/site-packages/numpy-1.23.2-py3.8-linux-x86_64.egg/numpy/core/_methods.py", line 44, in _amin
>     return umr_minimum(a, axis, None, out, keepdims, initial, where)
> ValueError: zero-size array to reduction operation minimum which has no identity

This is because in "check_specific_stopping_critera" (in parameter_space.py), line 588 makes last_iter=0 (since the previous one was 1) and it is not stopped by " if last_iter < 0: return" in line 592/593. Since there is no iter 0, the masked models table is empty and I get the error. 

Modifying "if last_iter < 0" to "if last_iter <= 0" (same as line 584) fixed the error for me.

**Comment by maindlt** [comment]
Hi @gsantucci90,

many thanks for bringing this up :-)

Carefully looking at `check_specific_stopping_criteria()` it _should_ work with "if last_iter < 0" because last_iter=0 _should_ result in a nonzero mask because running DYNAMITE again will read the which_iter=0 entries in the all_models table and will compare the chi2 values from that iteration with the new ones... But it does not work...

My guess is that probably it may be connected to the model iterator that combines iterations 0 and 1 into one run incrementing the iteration counter by 2 in the beginning, but that does not explain why your example works with "if last_iter <= 0" in line 592...

Another guess: more users will have the problem continuing after a one-iteration run. Could you perhaps share a (small orblib for short running time...) example via Slack so we can debug?

Many thanks and cheers,
Thomas

Side note: also, we may have to revisit `check_specific_stopping_criteria()` in a future development meeting to make sure it works as intended in case there are iterations that result in all chi2=nan...

**Comment by maindlt** [comment]
Closed due to inactivity - please feel free to reopen/create a new issue if the problem comes back to life.
