### ISSUE TITLE
genfromtxt orblib_read error with dithering 3

### ISSUE THREAD

**Issue by sthater** [dynamics-of-stellar-systems/dynamite#297]
When running DYNA with dithering 3, we had the case that in the orbit_plot the orbit library could not be read anymore. This has probably to do with fortran formatting the output in a way that is not correctly being read by python. In fact, the corresponding file has different column length in different rows.

genfromtxt has probably be exchanged for a different file-reader. Giulia and Prash mentioned that they had a solution.

Error: 
Traceback (most recent call last):
  File "/gpfs/data/fs71474/sthater/Dynamite/PGC1021091/test_sabine.py", line 126, in <module>
    run_user_test()
  File "/gpfs/data/fs71474/sthater/Dynamite/PGC1021091/test_sabine.py", line 121, in run_user_test
    fig2 = plotter.orbit_plot(Rmax_arcs=20)
  File "/home/fs71474/sthater/.local/lib/python3.9/site-packages/dynamite/plotter.py", line 1440, in orbit_plot
    orbclass1 = np.genfromtxt(file2).T
  File "/home/fs71474/sthater/.local/lib/python3.9/site-packages/numpy-1.21.1-py3.9-linux-x86_64.egg/numpy/lib/npyio.py", line 2124, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #6 (got 10 columns instead of 25)
    Line #12 (got 10 columns instead of 25)
    Line #18 (got 10 columns instead of 25)
    Line #24 (got 10 columns instead of 25)
    Line #30 (got 10 columns instead of 25)
    Line #36 (got 10 columns instead of 25)
    Line #42 (got 10 columns instead of 25)
    Line #48 (got 10 columns instead of 25)
    Line #54 (got 10 columns instead of 25)
    Line #60 (got 10 columns instead of 25)
    Line #66 (got 10 columns instead of 25)
    Line #72 (got 10 columns instead of 25)

**Comment by sthater** [comment]
Errors for plotter.orbit_distribution() and plotter.orbit_plot(Rmax_arcs=20)

![Uploading Screenshot 2023-05-12 at 16.59.12.png…]()

**Comment by maindlt** [comment]
Hi all, I tested with `test_nnls.py` and `dithering: 3` in its yaml file.
- Result Plotter.orbit_plot(Rmax_arcs=20):
Current master branch: I get the same errors that Sabine reports in her original post (`Line #6 (got 10 columns instead of 25)` etc.).
Current branch orblib_read_error (PR #298): no errors, plot displays ok.
- Result Plotter.orbit_distribution(): no errors in either branch, plots display ok.

Next step: find out why Sabine gets the errors in the plotting routines...

**Comment by maindlt** [comment]
Found the solution: The problem was that the config file used for creating the plots was different from the config file used for creating the models. Specifically, the `orblib_settings` don't match: the config file in the main directory has the settings

```
orblib_settings:
    nE: 63
    nI2: 30
    nI3: 21
    dithering: 1
```

and the config files used for creating the orblibs which were automatically backed up in the `.../Output_d3/.../mlxx.x` folders have

```
orblib_settings:
    nE: 21
    nI2: 10
    nI3: 7
    dithering: 3
```

Because correctly reading the files `orblib.dat_orbclass.out` and `orblibbox.dat_orbclass.out` requires the correct orblib sizes DYNAMITE fails.

I tried to create the plots with the correct config files and it worked for me on the cluster and my Mac.

Please verify and if so, we can merge PR #298 (which is still needed to fix the reading process itself) and close this issue.
