### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by astro19962023** [dynamics-of-stellar-systems/dynamite#359]
While compiling fortran program in make all step I am getting following error
collect2: error: ld returned 1 exit status
make: *** [Makefile:278: triaxnnls_CRcut] Error 1
I amm attaching screenshot also

![Screenshot from 2023-12-27 19-35-48](https://github.com/dynamics-of-stellar-systems/dynamite/assets/154993641/053d138a-c179-4b3f-a34a-e0a91e2419cf)
![Screenshot from 2023-12-27 19-35-58](https://github.com/dynamics-of-stellar-systems/dynamite/assets/154993641/6819f1f0-d960-4886-9ab0-2fddcb0979d0)

**Comment by maindlt** [comment]
Hello @astro19962023,
your screenshot looks like it is taken from an Ubuntu system; unfortunately there have been issues with GALAHAD on Ubuntu in the past. As in the past months we were working toward eliminating the need for GALAHAD, I would recommend you build DYNAMITE without GALAHAD, using the Python NNLS weight solver in your config files:
- Option 1: use the latest official release DYNAMITE 4.1.0.
For this, just get the 4.1.0 version from GitHub and follow the installation guide option (B). In essence, this skips compiling GALAHAD and instead of `make all` you say `make nogal` when building the executables in `legacy_fortran/`. Disadvantage of this method: (1) the beta plots won't work, (2) most example `*.yaml` configuration files still have `type: "LegacyWeightSolver"` and `nnls_solver: 1` in their `weight_solver_settings:` section. These need to be changed to `type: "NNLS"`and `nnls_solver: 'scipy'`, respectively.
- Option 2 (recommended): use the latest version of the master branch (which contains the latest tested version of DYNAMITE with features and bugfixes that will go into the next release).
For this, just pull the latest version of the master branch or go to https://github.com/dynamics-of-stellar-systems/dynamite and say `<> Code` -> `Download ZIP` and follow the installation guide option (B). In essence, this skips compiling GALAHAD and instead of `make all` you say `make nogal` when building the executables in `legacy_fortran/`. Advantage of this method: you get the beta plots working, the example `*.yaml` configuration files have the new Python weight solver set up and you get additional bugfixes ;-)

Does this work for you?
All the best, Thomas

**Comment by maindlt** [comment]
Closed for now, please re-open in case the error persists...
